name: blog-features-allon-on-streaming
image_uri: anyscale/ray-llm:nightly-py311-cu128
cloud: anyscale_v2_default_cloud
compute_config:
  cloud: anyscale_v2_default_cloud
  head_node:
    instance_type: m8a.xlarge
  worker_nodes:
    - instance_type: m7a.4xlarge
      min_nodes: 1
      max_nodes: 1
env_vars:
  ANYSCALE_TRACING_EXPORTER_IMPORT_PATH: ""
  RAY_SERVE_ENABLE_HA_PROXY: "1"
  ANYSCALE_RAY_SERVE_ENABLE_HA_PROXY: "1"
  RAY_SERVE_HAPROXY_TCP_NODELAY: "1"
  RAY_SERVE_THROUGHPUT_OPTIMIZED: "1"
applications:
  - name: app1
    route_prefix: /
    runtime_env:
      working_dir: ../../streaming_app/
    import_path: app:app
    deployments:
      - name: GrandChildDeployment
        max_ongoing_requests: 10000
        num_replicas: 1
      - name: MyDeployment
        max_ongoing_requests: 10000
        num_replicas: 1
