name: blog-features-allon-off-streaming
image_uri: anyscale/ray-llm:nightly-py311-cu128
cloud: anyscale_v2_default_cloud
compute_config: seiji-perf-bench
env_vars:
  ANYSCALE_TRACING_EXPORTER_IMPORT_PATH: ""
applications:
  - name: app1
    route_prefix: /
    runtime_env:
      working_dir: ../../../streaming/
    import_path: app:app
    deployments:
      - name: GrandChildDeployment
        max_ongoing_requests: 10000
        num_replicas: 1
      - name: MyDeployment
        max_ongoing_requests: 10000
        num_replicas: 1
