name: blog-features-grpc-off-unary
image_uri: anyscale/ray-llm:nightly-py311-cu128
cloud: anyscale_v2_default_cloud
compute_config: seiji-perf-bench
env_vars:
  ANYSCALE_TRACING_EXPORTER_IMPORT_PATH: ""
applications:
  - name: default
    route_prefix: /
    runtime_env:
      working_dir: ../../../test_service/
    import_path: fastapi_dep:entrypoint
    deployments:
      - name: Echo
        max_ongoing_requests: 100000
        num_replicas: 1
      - name: ASGIIngressDeployment
        max_ongoing_requests: 100000
        num_replicas: 1
